### ISSUE TITLE
Add "door open for 5min"

### ISSUE THREAD

**Issue by hwikene** [UbhiTS/ad-alexadoorwindowannounce#1]
Hi! is it possible to add a delay that Alexa only speak when door or window have been open for -/+ 5min?

**Comment by UbhiTS** [comment]
sure, I can add that. will get to it soon, give me a couple of days. hopefully sooner !

**Comment by UbhiTS** [comment]
Can you please test v1.0.6. I've added two new parameters under announcements, delay and close. Set the delay to whatever minutes or seconds you want, and also you can control if you want closing announcements by setting the close parameter to True or False

**Comment by hwikene** [comment]
Great! Awesome job :)
