### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by AtomicLaser** [UbhiTS/ad-alexadoorwindowannounce#2]
I usually do my Door Open announcements in Home Assistant as part of an automation, combined with Alexa media player, however this stopped working where I have two groups of Alexa devices in the home on different login accounts and will only work to one account

Tried this one and must say it works like a dream with two separate amazon login accounts, however there is a niggling issue, where my automations will fire immediately, this seems to have a lengthily delay on when any doors are triggered.

Is there a way to get the delay down, if it was almost instant like my automations were, I'd definitely use this!   

In addition a nice on/off button for Lovelace would be great too for those times when the door announcements are a bit receptive!

**Comment by UbhiTS** [comment]
Hi, thanks for trying this out. I'm unable to comprehend why it's giving a lag in your case. In my case, the door or window announcement is instant. I'm using a RPi 3B+ using HassIO. Can we do a remote debug, what do your logs say ?

**Comment by UbhiTS** [comment]
Also, I'm using ZWave door / Window sensors from EcoLink, just FYI ... what are the sensors you are using ?

**Comment by UbhiTS** [comment]
And how much delay are we talking about ?

**Comment by UbhiTS** [comment]
Closing because of no response. If the issue persists, please feel free to reopen this issue or submit a new one. Thanks
